linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  gocyclo:
    min-complexity: 20
  goconst:
    min-len: 8
    min-occurrences: 12
  lll:
    line-length: 120
  govet:
    check-shadowing: true
  exhaustive:
    default-signifies-exhaustive: true
linters:
  enable-all: true
  fast: false
  disable:
    - depguard
    - nlreturn
    - nonamedreturns
    - perfsprint
    - varnamelen
    - wsl
    # deprecated
    - deadcode
    - ifshort
    - interfacer
    - exhaustivestruct
    - maligned
    - structcheck
    - varcheck
    - scopelint
    - nosnakecase
    - golint
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-use-default: true
  exclude:
    - "any new system should use AES"
    - 'Magic number: 8\D '
    - 'Magic number: 512\D '
